name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0  # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@32110d4e311bd8996b2a82bf2a43b714ccc91777 # v1.221.0
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "SPEC_TEST=_site_no_baseurl" >> $GITHUB_ENV
          fi

      - name: Build Site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll b

          if [[ -n $SPEC_TEST ]]; then
            # Bypass the defects of htmlproofer
            bundle exec jekyll b -b "" -d "$SPEC_TEST"
          fi

      - name: Test Site
        run: |
          if [[ -n $SPEC_TEST ]]; then
            bash tools/test.sh -d "$SPEC_TEST"
          else
            bash tools/test.sh
          fi

      - name: Deploy
        run: |
          bash tools/deploy.sh
